on:
  workflow_call:
    inputs:
      image-suffix:
        type: string
        description: The suffix of the image, e.g. ghcr.io/org/<suffix>
      image-tags:
        default: |
          type=schedule,pattern=weekly
          type=schedule,pattern=weekly-{{date 'YYYYMMDD'}}
          type=ref,event=branch
          type=ref,event=tag
          type=ref,event=pr
          type=sha,prefix=sha-,format=short
          type=raw,value=latest,enable={{is_default_branch}}
        type: string
        description: Zero or many tags to use. Different tags should be separated by new lines. See https://github.com/docker/metadata-action#tags-input
      push-image:
        type: boolean
        default: true
        description: Set to true if this action should attempt to push/cache the build image.
      build-context:
        type: string
        description: The build context to use for the build. See https://github.com/docker/build-push-action#usage
      build-file:
        type: string
        description: The build file to use for the build. See https://github.com/docker/build-push-action#inputs
      build-args:
        type: string
        description: The build args to use for the build. See https://github.com/docker/build-push-action#inputs
      build-target:
        type: string
        description: The build target to use for the build. See https://github.com/docker/build-push-action#inputs
      build-always-pull:
        type: boolean
        default: true
        description: If the build should always pull referenced images. See https://github.com/docker/build-push-action#inputs

jobs:
  publish-github:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/${{ github.repository }}${{ inputs.image-suffix && format('/{0}', inputs.image-suffix) || ''}}
    steps:
      - uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
        with:
          install: true
          version: latest
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: ${{ env.IMAGE }}
          tags: ${{ inputs.image-tags }}
      - uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        id: build
        with:
          file: ${{ inputs.build-file }}
          context: ${{ inputs.build-context }}
          push: ${{ inputs.push-image }}
          pull: ${{ inputs.build-always-pull }}
          target: ${{ inputs.build-target }}
          cache-from: ${{ inputs.push-image && format('type=registry,ref={0}:cache', env.IMAGE) || ''}}
          cache-to: ${{ inputs.push-image && format('type=registry,ref={0}:cache,mode=max', env.IMAGE) || ''}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
